# Generated by Django 5.2.8 on 2025-11-20 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('ID_Responsavel', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=100)),
                ('CPF', models.CharField(max_length=14, unique=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('Telefone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('ID_Aluno', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=100)),
                ('DataNascimento', models.DateField()),
                ('NivelEscolar', models.CharField(max_length=50)),
                ('ObservacoesProgresso', models.TextField(blank=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos_associados', to='alunos.responsavel')),
            ],
        ),
    ]
