# Generated by Django 5.2.8 on 2025-12-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='NivelEscolar',
            field=models.CharField(choices=[('1_ANO_FUNDAMENTAL', '1º ano do Ensino Fundamental'), ('2_ANO_FUNDAMENTAL', '2º ano do Ensino Fundamental'), ('3_ANO_FUNDAMENTAL', '3º ano do Ensino Fundamental'), ('4_ANO_FUNDAMENTAL', '4º ano do Ensino Fundamental'), ('5_ANO_FUNDAMENTAL', '5º ano do Ensino Fundamental'), ('6_ANO_FUNDAMENTAL', '6º ano do Ensino Fundamental'), ('7_ANO_FUNDAMENTAL', '7º ano do Ensino Fundamental'), ('8_ANO_FUNDAMENTAL', '8º ano do Ensino Fundamental'), ('9_ANO_FUNDAMENTAL', '9º ano do Ensino Fundamental'), ('ENSINO_MEDIO', 'Ensino Médio'), ('SUPERIOR', 'Ensino Superior'), ('EJA', 'Educação de Jovens e Adultos (EJA)'), ('OUTRO', 'Outro')], db_index=True, default='OUTRO', max_length=50),
        ),
    ]
