# Generated by Django 5.2.8 on 2025-11-20 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('ID_Categoria', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('ID_Material', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=150)),
                ('Descricao', models.TextField(blank=True)),
                ('Arquivo', models.FileField(upload_to='materiais_didaticos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiais_classificados', to='materiais.categoria')),
            ],
        ),
    ]
