# Generated by Django 5.2.8 on 2025-12-14 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import datetime
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='data_upload',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now), 
            preserve_default=False, 
        ),
        migrations.AddField(
            model_name='material',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materiais_didaticos', to=settings.AUTH_USER_MODEL),
            preserve_default=False, 
        ),
    ]
