# Generated by Django 5.2.8 on 2025-12-14 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0002_material_data_upload_material_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais_classificados', to='materiais.categoria'),
        ),
        migrations.AlterField(
            model_name='material',
            name='data_upload',
            field=models.DateTimeField(),
        ),
    ]
