# Generated by Django 5.2.8 on 2025-12-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0003_alter_material_categoria_alter_material_data_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='data_upload',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
