# Generated by Django 5.2.8 on 2025-11-20 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('ID_Pacote', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=100)),
                ('Descricao', models.TextField(blank=True)),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('QuantidadeAulas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('ID_Pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('DataPagamento', models.DateField(auto_now_add=True)),
                ('ValorPago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Metodo', models.CharField(max_length=50)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_realizados', to='alunos.aluno')),
                ('pacote', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamento_referente', to='financeiro.pacote')),
            ],
        ),
    ]
