# Generated by Django 5.2.8 on 2025-11-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('ID_Aula', models.AutoField(primary_key=True, serialize=False)),
                ('Data', models.DateField()),
                ('HoraInicio', models.TimeField()),
                ('HoraFim', models.TimeField()),
                ('Conteudo', models.TextField(blank=True)),
                ('Status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=10)),
                ('alunos_participantes', models.ManyToManyField(related_name='aulas_participadas', to='alunos.aluno')),
                ('materiais_usados', models.ManyToManyField(related_name='aulas_que_usam', to='materiais.material')),
            ],
        ),
    ]
