# Generated by Django 5.2.8 on 2025-12-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='materiais_usados',
            field=models.ManyToManyField(blank=True, related_name='aulas_que_usam', to='materiais.material'),
        ),
    ]
