# Generated by Django 5.2.8 on 2025-12-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
